name: ACR_Build_Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.POC_REGISTRY_CREDENTIALS }}
    
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.POC_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.POC_REGISTRY_USERNAME }}
        password: ${{ secrets.POC_REGISTRY_PASSWORD }}
    - run: |
        az acr build . -t ${{ secrets.POC_REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.POC_RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.POC_RESOURCE_GROUP }}${{ github.run_number }}
        image: ${{ secrets.POC_REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
        registry-login-server: ${{ secrets.POC_REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.POC_REGISTRY_USERNAME }}
        registry-password: ${{ secrets.POC_REGISTRY_PASSWORD }}
        name: aci-sampleapp
        location: 'central us'
